// Encrypts the private plan page for /api/plan (dev only; excluded from Vercel by .vercelignore).
//
//   node dev/encrypt-plan.js
//
// Reads docs/plan-page.html (git-ignored plaintext) and writes api/_plan-data.js, which is safe to
// commit: it's AES-256-GCM ciphertext. The key comes from PLAN_KEY (32 random bytes, base64) in the
// environment or in .env.local (git-ignored). Use the same PLAN_KEY as in Vercel, or the page
// won't decrypt there. Re-run this after every change to the plan page.
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "docs", "plan-page.html");
const OUT = path.join(ROOT, "api", "_plan-data.js");

function loadEnvLocal() {
  const f = path.join(ROOT, ".env.local");
  if (!fs.existsSync(f)) return;
  for (const line of fs.readFileSync(f, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}

loadEnvLocal();
const key = Buffer.from((process.env.PLAN_KEY || "").trim(), "base64");
if (key.length !== 32) {
  console.error("PLAN_KEY must be 32 random bytes in base64 (set it in the environment or .env.local).");
  process.exit(1);
}
if (!fs.existsSync(SRC)) {
  console.error(`Missing ${path.relative(ROOT, SRC)} (the plaintext plan page).`);
  process.exit(1);
}

const iv = crypto.randomBytes(12);
const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
const data = Buffer.concat([cipher.update(fs.readFileSync(SRC)), cipher.final()]);
const tag = cipher.getAuthTag();

fs.writeFileSync(OUT, `/* Encrypted MVP plan page (AES-256-GCM). Generated by dev/encrypt-plan.js; don't edit by hand.
   Decrypted only by api/plan.js with PLAN_KEY, after the password check. */
module.exports = {
  updated: ${JSON.stringify(new Date().toISOString().slice(0, 10))},
  iv: ${JSON.stringify(iv.toString("base64"))},
  tag: ${JSON.stringify(tag.toString("base64"))},
  data: ${JSON.stringify(data.toString("base64"))},
};
`);
console.log(`Wrote ${path.relative(ROOT, OUT)} (${data.length} bytes encrypted).`);
